---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sample
  name: sample
spec:
  containers:
  - image: yuriao/devops:IMAGE_TAG
    imagePullPolicy: IfNotPresent
    name: sample
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: sample
  name: sample
spec:
  ports:
  - port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    run: sample
  type: ClusterIP
